# This Makefile is generated by omake: https://github.com/ouonline/omake.git

AR := ar
CXX := g++

ifeq ($(debug), y)
	CXXFLAGS := -g
else
	CXXFLAGS := -O2 -DNDEBUG
endif
CXXFLAGS := $(CXXFLAGS) -Wall -Werror -Wextra -fPIC

TARGET := libluacpp.a libluacpp.so

.PHONY: all clean

all: $(TARGET)

luacpp_OBJS := luacpp.cpp.luacpp.o

luacpp_INCLUDE := -I../../../lua

luacpp_LIBS := ../../../lua/src/liblua.a -ldl -lm

luacpp.cpp.luacpp.o: luacpp.cpp
	$(CXX) $(CXXFLAGS) $(luacpp_INCLUDE) -c $< -o $@

libluacpp.a: $(luacpp_OBJS)
	$(AR) rc $@ $^

libluacpp.so: $(luacpp_OBJS)
	$(CXX) -shared -o $@ $^ $(luacpp_LIBS)

clean:
	rm -f $(TARGET) $(luacpp_OBJS)
